### ISSUE TITLE
Crashes instantly after starting it Windows 8 64bit

### ISSUE THREAD

**Issue by mineace** [d2rm/d2rm#5]

**Comment by pyarmak** [comment]
I need your logs in order to do anything.

**Comment by mineace** [comment]
Idk how to get the logs :/ sry

**Comment by pyarmak** [comment]
Oh not a problem, they are found in:
C:\Users\ <USERNAME>\AppData\Local\D2RM
There should be two log files, dota.log and exceptions.log
I have reopened this issue. 
I'm gearing up for a major release so I'd really like to take a look at the logs before so that I don't potentially have to patch right after.

Thank you for taking the time to report the bug.

**Comment by Dominitia** [comment]
I have the same issue, on Windows 8 x64, and Windows 10 x64 build 9879. The program worked until I filled in the API key and a couple test profiles. When I tried to save the changes it crashed and now crashes on start up with no warnings or errors. I only have access to my Windows 10 computer right now but these are the logs from it since you're in a hurry:

Dota: http://pastebin.com/xz8jajgy

Exceptions: http://pastebin.com/0J58zGHx

**Comment by pyarmak** [comment]
Dominitia, it looks like your issue is also related to the ursa module.
Could you tell me what is found (if anything) under this path:
G:\\Programs\\D2RM\\app\\node_modules\\steam\\node_modules\\ursa\\bin\\

**Comment by Dominitia** [comment]
ursaNative.node is the only file.

**Comment by pyarmak** [comment]
Yeah that's the only file that's supposed to be in there but it says in the log that the app can't find it (but it gives the right path!).
This is a very confounding error. I may go and open a ticket on the ursa github repo to ask for some help if I can't figure this out.
The worst part is that no matter what I do, I can't replicate this error.

**Comment by Dominitia** [comment]
I just tried replicating it a few different ways in a sandbox. It didn't work on Windows 8.1, but it did work in WIndows 7. Is it possible Windows 8 and newer changed how they interact with node.js?

I also tried a complete reinstall in Windows 10, and by installing to the default directory ...\appdata\roaming\D2RM I got it to go a little farther in that it seemed to try to search for replays for a few seconds before crashing. Restarting froze the program and required manually closing. Changing to an alternative directory resulted in the instant crashes again.

**Comment by pyarmak** [comment]
Interesting. Could you grab the Windows 10 logs for me? 
I'm very interested in those because I'm actually developing on a windows 10 machine right now.
That being said I don't think it is a windows 8 and newer issue since it runs perfectly on my windows 10 machine. 
For some reason virtualbox doesn't like playing nice with windows 10 hosts yet so I can't really run any VMs to test this stuff out. I might just boot into a portable linux distro later when I have some free time.

**Comment by Dominitia** [comment]
The logs I sent last were from Windows 10 since I couldn't access Windows 8 at the time. Or did you mean different logs?

**Comment by pyarmak** [comment]
I am closing all issues as I have tried addressing them in 0.2.0
